export enum ApartmentTypes {
    STUDIO_APARTMENT = "STUDIO_APARTMENT",
    FLAT = "FLAT",
    LUXURIOUS_APARTMENT = "LUXURIOUS_APARTMENT",
    APARTMENT = "APARTMENT",
    SEMI_DETACHED_DUPLEX = "SEMI_DETACHED_DUPLEX"
}