export enum PaymentStatuses {
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED",
    FAILED = "FAILED",
    REFUNDED = "REFUNDED",
    INITIALIZED = "INITIALIZED",
    CANCELLED = "CANCELLED",
    EXPIRED = "EXPIRED"
}