import { MigrationInterface, QueryRunner } from "typeorm";

export class TimestampChange1692812898581 implements MigrationInterface {
    name = 'TimestampChange1692812898581'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "faq_question" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "faq_question" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faq_question" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "faq_question" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "expiration_date"`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "expiration_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_media" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_media" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_media" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_media" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "verification_date"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "verification_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faq" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "faq" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faq" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "faq" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lessor_info" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lessor_info" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lessor_info" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lessor_info" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_fee" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_fee" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_fee" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_fee" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unit" DROP COLUMN "date_available"`);
        await queryRunner.query(`ALTER TABLE "unit" ADD "date_available" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "unit" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "unit" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unit" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "unit" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property" DROP COLUMN "date_available"`);
        await queryRunner.query(`ALTER TABLE "property" ADD "date_available" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "property" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "review" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "review" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "review" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "review" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property" DROP COLUMN "date_available"`);
        await queryRunner.query(`ALTER TABLE "property" ADD "date_available" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "unit" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "unit" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unit" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "unit" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unit" DROP COLUMN "date_available"`);
        await queryRunner.query(`ALTER TABLE "unit" ADD "date_available" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "property_fee" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_fee" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_fee" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_fee" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lessor_info" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lessor_info" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lessor_info" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lessor_info" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faq" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "faq" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faq" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "faq" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "verification_date"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "verification_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_tour_availability" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_media" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_media" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_media" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_media" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "expiration_date"`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "expiration_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "faq_question" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "faq_question" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faq_question" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "faq_question" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
    }

}
