import { MigrationInterface, QueryRunner } from "typeorm";

export class EnumMod1692892726312 implements MigrationInterface {
    name = 'EnumMod1692892726312'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "otp" ADD "is_used" boolean`);
        await queryRunner.query(`ALTER TYPE "public"."faq_type_enum" RENAME TO "faq_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."faq_type_enum" AS ENUM('QUESTION', 'LIST')`);
        await queryRunner.query(`ALTER TABLE "faq" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "faq" ALTER COLUMN "type" TYPE "public"."faq_type_enum" USING "type"::"text"::"public"."faq_type_enum"`);
        await queryRunner.query(`ALTER TABLE "faq" ALTER COLUMN "type" SET DEFAULT 'QUESTION'`);
        await queryRunner.query(`DROP TYPE "public"."faq_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."media_ref_category_enum" RENAME TO "media_ref_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."media_ref_category_enum" AS ENUM('PROPERTY', 'PROPERTY_APPLICATION')`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "ref_category" TYPE "public"."media_ref_category_enum" USING "ref_category"::"text"::"public"."media_ref_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_ref_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."media_media_type_enum" RENAME TO "media_media_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."media_media_type_enum" AS ENUM('AUDIO', 'VIDEO', 'IMAGE', 'DOCUMENT')`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "media_type" TYPE "public"."media_media_type_enum" USING "media_type"::"text"::"public"."media_media_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_media_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."media_media_category_enum" RENAME TO "media_media_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."media_media_category_enum" AS ENUM('GALLERY_IMAGE', 'PROFILE_IMAGE', 'GALLERY_VIDEO', 'LEASE_DOCUMENT')`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "media_category" TYPE "public"."media_media_category_enum" USING "media_category"::"text"::"public"."media_media_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_media_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."messages_status_enum" RENAME TO "messages_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum" AS ENUM('SENT', 'READ')`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "status" TYPE "public"."messages_status_enum" USING "status"::"text"::"public"."messages_status_enum"`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "status" SET DEFAULT 'SENT'`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."lessor_info_lessor_category_enum" RENAME TO "lessor_info_lessor_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."lessor_info_lessor_category_enum" AS ENUM('AGENT_OR_COMPANY', 'TENANT', 'LANDLORD')`);
        await queryRunner.query(`ALTER TABLE "lessor_info" ALTER COLUMN "lessor_category" TYPE "public"."lessor_info_lessor_category_enum" USING "lessor_category"::"text"::"public"."lessor_info_lessor_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lessor_info_lessor_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."otp_otp_ref_type_enum" RENAME TO "otp_otp_ref_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."otp_otp_ref_type_enum" AS ENUM('PHONE_NUMBER', 'EMAIL')`);
        await queryRunner.query(`ALTER TABLE "otp" ALTER COLUMN "otp_ref_type" TYPE "public"."otp_otp_ref_type_enum" USING "otp_ref_type"::"text"::"public"."otp_otp_ref_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."otp_otp_ref_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."property_fee_payment_type_enum" RENAME TO "property_fee_payment_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."property_fee_payment_type_enum" AS ENUM('MONTHLY', 'YEARLY', 'ONE_TIME', 'BASED_ON_USAGE')`);
        await queryRunner.query(`ALTER TABLE "property_fee" ALTER COLUMN "payment_type" TYPE "public"."property_fee_payment_type_enum" USING "payment_type"::"text"::"public"."property_fee_payment_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."property_fee_payment_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."unit_status_enum" RENAME TO "unit_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."unit_status_enum" AS ENUM('AVAILABLE', 'UNAVAILABLE', 'OCCUPIED')`);
        await queryRunner.query(`ALTER TABLE "unit" ALTER COLUMN "status" TYPE "public"."unit_status_enum" USING "status"::"text"::"public"."unit_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."unit_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."property_status_enum" RENAME TO "property_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."property_status_enum" AS ENUM('AVAILABLE', 'UNAVAILABLE', 'OCCUPIED')`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "status" TYPE "public"."property_status_enum" USING "status"::"text"::"public"."property_status_enum"`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "status" SET DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`DROP TYPE "public"."property_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."property_transaction_type_enum" RENAME TO "property_transaction_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."property_transaction_type_enum" AS ENUM('SHORT_TERM_RENTAL', 'LONG_TERM_RENTAL', 'ROOM_BUDDY_RENTAL', 'SALE')`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "transaction_type" TYPE "public"."property_transaction_type_enum" USING "transaction_type"::"text"::"public"."property_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."property_transaction_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."property_lease_term_enum" RENAME TO "property_lease_term_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."property_lease_term_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "lease_term" TYPE "public"."property_lease_term_enum" USING "lease_term"::"text"::"public"."property_lease_term_enum"`);
        await queryRunner.query(`DROP TYPE "public"."property_lease_term_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."service_fee_config_transaction_type_enum" RENAME TO "service_fee_config_transaction_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."service_fee_config_transaction_type_enum" AS ENUM('SHORT_TERM_RENTAL', 'LONG_TERM_RENTAL', 'ROOM_BUDDY_RENTAL', 'SALE')`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" ALTER COLUMN "transaction_type" TYPE "public"."service_fee_config_transaction_type_enum" USING "transaction_type"::"text"::"public"."service_fee_config_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."service_fee_config_transaction_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."review_type_enum" RENAME TO "review_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."review_type_enum" AS ENUM('SYSTEM', 'LANDLORD')`);
        await queryRunner.query(`ALTER TABLE "review" ALTER COLUMN "type" TYPE "public"."review_type_enum" USING "type"::"text"::"public"."review_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."review_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_role_enum" RENAME TO "user_role_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_role_enum" AS ENUM('RENTER', 'LESSOR', 'LESSOR_RENTER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "role" TYPE "public"."user_role_role_enum" USING "role"::"text"::"public"."user_role_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('RENTER', 'LESSOR', 'LESSOR_RENTER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" TYPE "public"."user_role_enum" USING "role"::"text"::"public"."user_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_role_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "role" TYPE "public"."user_role_role_enum_old" USING "role"::"text"::"public"."user_role_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_role_enum_old" RENAME TO "user_role_role_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."review_type_enum_old" AS ENUM('0', '1')`);
        await queryRunner.query(`ALTER TABLE "review" ALTER COLUMN "type" TYPE "public"."review_type_enum_old" USING "type"::"text"::"public"."review_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."review_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."review_type_enum_old" RENAME TO "review_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."service_fee_config_transaction_type_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "service_fee_config" ALTER COLUMN "transaction_type" TYPE "public"."service_fee_config_transaction_type_enum_old" USING "transaction_type"::"text"::"public"."service_fee_config_transaction_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."service_fee_config_transaction_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."service_fee_config_transaction_type_enum_old" RENAME TO "service_fee_config_transaction_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."property_lease_term_enum_old" AS ENUM('0', '1')`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "lease_term" TYPE "public"."property_lease_term_enum_old" USING "lease_term"::"text"::"public"."property_lease_term_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."property_lease_term_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."property_lease_term_enum_old" RENAME TO "property_lease_term_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."property_transaction_type_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "transaction_type" TYPE "public"."property_transaction_type_enum_old" USING "transaction_type"::"text"::"public"."property_transaction_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."property_transaction_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."property_transaction_type_enum_old" RENAME TO "property_transaction_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."property_status_enum_old" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "status" TYPE "public"."property_status_enum_old" USING "status"::"text"::"public"."property_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "property" ALTER COLUMN "status" SET DEFAULT '0'`);
        await queryRunner.query(`DROP TYPE "public"."property_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."property_status_enum_old" RENAME TO "property_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."unit_status_enum_old" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`ALTER TABLE "unit" ALTER COLUMN "status" TYPE "public"."unit_status_enum_old" USING "status"::"text"::"public"."unit_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."unit_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."unit_status_enum_old" RENAME TO "unit_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."property_fee_payment_type_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "property_fee" ALTER COLUMN "payment_type" TYPE "public"."property_fee_payment_type_enum_old" USING "payment_type"::"text"::"public"."property_fee_payment_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."property_fee_payment_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."property_fee_payment_type_enum_old" RENAME TO "property_fee_payment_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."otp_otp_ref_type_enum_old" AS ENUM('0', '1')`);
        await queryRunner.query(`ALTER TABLE "otp" ALTER COLUMN "otp_ref_type" TYPE "public"."otp_otp_ref_type_enum_old" USING "otp_ref_type"::"text"::"public"."otp_otp_ref_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."otp_otp_ref_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."otp_otp_ref_type_enum_old" RENAME TO "otp_otp_ref_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."lessor_info_lessor_category_enum_old" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`ALTER TABLE "lessor_info" ALTER COLUMN "lessor_category" TYPE "public"."lessor_info_lessor_category_enum_old" USING "lessor_category"::"text"::"public"."lessor_info_lessor_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."lessor_info_lessor_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."lessor_info_lessor_category_enum_old" RENAME TO "lessor_info_lessor_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum_old" AS ENUM('0', '1')`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "status" TYPE "public"."messages_status_enum_old" USING "status"::"text"::"public"."messages_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "status" SET DEFAULT '0'`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."messages_status_enum_old" RENAME TO "messages_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."media_media_category_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "media_category" TYPE "public"."media_media_category_enum_old" USING "media_category"::"text"::"public"."media_media_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."media_media_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."media_media_category_enum_old" RENAME TO "media_media_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."media_media_type_enum_old" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "media_type" TYPE "public"."media_media_type_enum_old" USING "media_type"::"text"::"public"."media_media_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."media_media_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."media_media_type_enum_old" RENAME TO "media_media_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."media_ref_category_enum_old" AS ENUM('0', '1')`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "ref_category" TYPE "public"."media_ref_category_enum_old" USING "ref_category"::"text"::"public"."media_ref_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."media_ref_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."media_ref_category_enum_old" RENAME TO "media_ref_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."faq_type_enum_old" AS ENUM('0', '1')`);
        await queryRunner.query(`ALTER TABLE "faq" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "faq" ALTER COLUMN "type" TYPE "public"."faq_type_enum_old" USING "type"::"text"::"public"."faq_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "faq" ALTER COLUMN "type" SET DEFAULT '0'`);
        await queryRunner.query(`DROP TYPE "public"."faq_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."faq_type_enum_old" RENAME TO "faq_type_enum"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "is_used"`);
    }

}
