import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNewMigration1760097063291 implements MigrationInterface {
    name = 'AddNewMigration1760097063291'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "contact_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "fullname" character varying, "email" character varying, "phone_number" character varying, "topic" character varying, "message" character varying, CONSTRAINT "PK_d74ea9b4efcf950e4f98d14b173" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "demo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying, "description" character varying, "duration" character varying, "video_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d8d89f7764de19ec5a40a5f056" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "donation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "email" character varying, "amount" integer, "payment_reference" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25fb5a541964bc5cfc18fb13a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faq_question" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ed61cb1433527f5841ff662abe2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "location_state" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "name" character varying, CONSTRAINT "PK_d49d1f3394185be892cff2cd913" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "location_lga" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "name" character varying, "state_id" uuid, CONSTRAINT "PK_ed3789040ebb558bb48108f0241" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "location_wards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "name" character varying, "lga_id" uuid, CONSTRAINT "PK_5bbee26e70d2eea34ebcdc84fee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_property" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "report_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "property_id" character varying NOT NULL, "user_id" character varying NOT NULL, "reason" character varying NOT NULL, CONSTRAINT "PK_a0fa83a2b8ff99bf954878bf1b9" PRIMARY KEY ("id", "report_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."faq_type_enum" AS ENUM('QUESTION', 'LIST')`);
        await queryRunner.query(`CREATE TABLE "faq" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."faq_type_enum" DEFAULT 'QUESTION', "title" character varying, "answer" character varying, "list_response" character varying array, "entity_id" character varying, "faq_question_id" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d6f5a52b1a96dd8d0591f9fbc47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "waitlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "email" character varying NOT NULL, CONSTRAINT "PK_eef8388d650efa57e5eb3b30621" PRIMARY KEY ("id", "email"))`);
        await queryRunner.query(`CREATE TYPE "public"."kvp_key_enum" AS ENUM('AMENITY')`);
        await queryRunner.query(`CREATE TABLE "kvp" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "value" json, "key" "public"."kvp_key_enum" NOT NULL, CONSTRAINT "PK_d900f2ec6cf184bf6a6bcbde8f3" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "wishlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying, "property_id" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_620bff4a240d66c357b5d820eaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lessor_info_lessor_category_enum" AS ENUM('AGENT_OR_COMPANY', 'TENANT', 'LANDLORD')`);
        await queryRunner.query(`CREATE TABLE "lessor_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "lessor_category" "public"."lessor_info_lessor_category_enum", "first_name" character varying, "last_name" character varying, "email" character varying, "phone_number" character varying, "agency_name" character varying, CONSTRAINT "PK_7f35a8a50a02f89e8d8931ecb82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_ref_category_enum" AS ENUM('PROPERTY', 'PROPERTY_APPLICATION')`);
        await queryRunner.query(`CREATE TYPE "public"."media_media_type_enum" AS ENUM('AUDIO', 'VIDEO', 'IMAGE', 'DOCUMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."media_media_category_enum" AS ENUM('GALLERY_IMAGE', 'PROFILE_IMAGE', 'GALLERY_VIDEO', 'LEASE_DOCUMENT')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "public_url" character varying, "ref_id" character varying, "ref_category" "public"."media_ref_category_enum", "media_type" "public"."media_media_type_enum", "media_category" "public"."media_media_category_enum", "is_public" boolean, "size" double precision, "size_metric" character varying, "media_ext" character varying, "media_file_name" character varying, "uploaded_by" character varying, "is_temp" boolean, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."otp_otp_ref_type_enum" AS ENUM('PHONE_NUMBER', 'EMAIL')`);
        await queryRunner.query(`CREATE TABLE "otp" ("otp_ref" character varying NOT NULL, "otp" character varying, "otp_ref_type" "public"."otp_otp_ref_type_enum", "expiration_date" TIMESTAMP WITH TIME ZONE, "is_used" boolean, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0dc7a5ac23164ab84f708d2c9f1" PRIMARY KEY ("otp_ref"))`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum" AS ENUM('SENT', 'READ')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" character varying, "recipientid" character varying, "message" character varying, "status" "public"."messages_status_enum" DEFAULT 'SENT', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying, "last_name" character varying, "address" character varying, "is_verified" boolean, "verification_date" TIMESTAMP WITH TIME ZONE, "profile_picture_url" character varying, "user_info" json, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fb08394d3f499b9e441cab9ca51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tour_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "meet_date" date, "email" character varying DEFAULT false, "phone" character varying DEFAULT false, "prefer_virtual_tour" boolean DEFAULT false, "property_id" uuid, "unit_id" uuid, "user_details_id" uuid, CONSTRAINT "PK_a46c26b890515f0046f46717edf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."property_lease_term_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TYPE "public"."property_status_enum" AS ENUM('AVAILABLE', 'UNAVAILABLE', 'OCCUPIED')`);
        await queryRunner.query(`CREATE TYPE "public"."property_transaction_type_enum" AS ENUM('SHORT_TERM_RENTAL', 'LONG_TERM_RENTAL', 'ROOM_BUDDY_RENTAL', 'SALE')`);
        await queryRunner.query(`CREATE TYPE "public"."property_type_enum" AS ENUM('HOUSE', 'CONDO', 'TOWNHOUSE', 'FLAT', 'BUNGALOW', 'SELFCON', 'SERVICES', 'SHARED', 'DUPLEX', 'STUDIO')`);
        await queryRunner.query(`CREATE TABLE "property" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "address" character varying, "lga" text, "floor_number" text, "area" text, "address_id" character varying, "advertised_unit" json, "amenities" character varying array, "availability" json, "caution_fee" json, "coordinates" point, "description" character varying, "faq" json, "city" character varying, "close_to_noise" boolean, "is_address_verified" boolean, "is_archived" boolean DEFAULT false, "is_complete" boolean NOT NULL DEFAULT false, "is_disabled" boolean NOT NULL DEFAULT false, "is_verified" boolean DEFAULT true, "landlord_resides" boolean, "lease_term" "public"."property_lease_term_enum", "lessor_document_id" uuid, "lessor_info_id" uuid, "lease_policy" json, "lessor_user_id" uuid, "religious_building" boolean, "sponsorship_level" smallint, "state" character varying, "status" "public"."property_status_enum" DEFAULT 'AVAILABLE', "tags" character varying array, "tour_availability" json, "tour_link" text, "transaction_type" "public"."property_transaction_type_enum", "type" "public"."property_type_enum", "utilities" json, "property_media_id" uuid, CONSTRAINT "REL_61769005fc1e66c57ea29f11fa" UNIQUE ("property_media_id"), CONSTRAINT "PK_d80743e6191258a5003d5843b4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."unit_status_enum" AS ENUM('AVAILABLE', 'UNAVAILABLE', 'OCCUPIED')`);
        await queryRunner.query(`CREATE TABLE "unit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "agency_fee_percentage" numeric, "fixed_agency_fee" numeric, "has_agency_fee" boolean DEFAULT false, "label" character varying, "no_of_bathrooms" numeric, "no_of_bathrooms_ensuite" numeric, "no_of_bedrooms" numeric, "payment_schedule" character varying, "price" numeric, "square_feet" numeric, "application_approved" boolean NOT NULL DEFAULT false, "is_unit_occupied" boolean NOT NULL DEFAULT false, "is_locked" boolean NOT NULL DEFAULT false, "locked_by" character varying, "lock_expires_at" TIMESTAMP WITH TIME ZONE, "is_paid" boolean NOT NULL DEFAULT false, "paid_until" TIMESTAMP WITH TIME ZONE, "status" "public"."unit_status_enum" DEFAULT 'AVAILABLE', "date_available" TIMESTAMP WITH TIME ZONE, "property_id" uuid, CONSTRAINT "PK_4252c4be609041e559f0c80f58a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "property_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "image_urls" character varying array DEFAULT '{}', "lease_document_url" character varying, "use_let_bud_template" boolean DEFAULT false, "video_urls" character varying array DEFAULT '{}', "media_ids" character varying array DEFAULT '{}', "lease_document_name" character varying, CONSTRAINT "PK_d18a71a690f74cc103387bd67df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('RENTER', 'LESSOR', 'LESSOR_RENTER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "phone_number" character varying, "username" character varying, "password" character varying, "details_id" character varying, "role" "public"."user_role_enum", "is_active" boolean, "sign_in_type" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_details_id" uuid, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_01eea41349b6c9275aec646eee0" UNIQUE ("phone_number"), CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "REL_d05063db688ad262c5c7a7482c" UNIQUE ("user_details_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request_to_rent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "first_name" character varying, "middle_name" character varying, "last_name" character varying, "identification_mode" character varying, "email" character varying, "phone_number" character varying, "summary" text, "num_people_living" integer, "num_co_tenants_above18" integer, "co_tenants" jsonb, "has_pets" boolean, "pet_type" character varying, "num_pets" integer, "move_in_date" date, "current_address" text, "switch_reason" text, "property_manager_name" character varying, "property_manager_contact" character varying, "past_address" text, "past_move_in_date" date, "past_move_out_date" date, "reason_for_leaving" text, "past_property_manager_contact" character varying, "current_salary_estimate" text, "workplace" character varying, "start_date_at_company" date, "company_referee_name" character varying, "referee_email" character varying, "referee_phone_number" character varying, "evicted_before" boolean, "eviction_reason" text, "convicted_before" boolean, "conviction_details" text, "emergency_contact_name" text, "relationship_with_contact" text, "emergency_contact_email" text, "emergency_contact_phone_number" text, "is_complete" boolean, "is_approve" boolean DEFAULT false, "lease_agreement_signed" boolean NOT NULL DEFAULT false, "lease_agreement_signed_at" TIMESTAMP, "application_withdrawn" boolean DEFAULT false, "withdrawn_at" TIMESTAMP, "user_id" uuid, "property_id" uuid, "unit_id" uuid, "user_details_id" uuid, CONSTRAINT "PK_fbd79e8a5cc18667ef7aaa78ccf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payee_role_enum" AS ENUM('lessor', 'rental', 'lessor_rental', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'FAILED', 'REFUNDED', 'INITIALIZED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payee_role" "public"."payments_payee_role_enum" NOT NULL DEFAULT 'admin', "property_id" uuid, "unit_id" uuid, "amount" integer NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'INITIALIZED', "reference" character varying NOT NULL, "email" character varying NOT NULL, "access_code" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "payer_id" uuid NOT NULL, "payee_id" uuid, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_fee_config_transaction_type_enum" AS ENUM('SHORT_TERM_RENTAL', 'LONG_TERM_RENTAL', 'ROOM_BUDDY_RENTAL', 'SALE')`);
        await queryRunner.query(`CREATE TABLE "service_fee_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transaction_type" "public"."service_fee_config_transaction_type_enum", "min_price" integer, "max_price" integer, "percentage" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a9567b248d677034bb1416a83c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."review_type_enum" AS ENUM('SYSTEM', 'LANDLORD')`);
        await queryRunner.query(`CREATE TABLE "review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying, "type" "public"."review_type_enum", "comment" character varying, "rating" smallint, "landlord_id" character varying, "question" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_role_enum" AS ENUM('RENTER', 'LESSOR', 'LESSOR_RENTER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user_role" ("role" "public"."user_role_role_enum" NOT NULL, "label" character varying, "config" character varying, "info" json, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_30ddd91a212a9d03669bc1dee74" PRIMARY KEY ("role"))`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('TRASFER', 'REFUND', 'PENDING', 'CONFIRMED', 'COMPLETED', 'INITIALIZED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" integer NOT NULL, "status" "public"."transactions_status_enum" DEFAULT 'TRASFER', "reference" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "request_to_rent_id" uuid NOT NULL, "payment_id" uuid, CONSTRAINT "REL_464da95dc8a05470b2b158d4df" UNIQUE ("payment_id"), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."property_fee_payment_type_enum" AS ENUM('MONTHLY', 'YEARLY', 'ONE_TIME', 'BASED_ON_USAGE')`);
        await queryRunner.query(`CREATE TABLE "property_fee" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fee_description" character varying, "payment_type" "public"."property_fee_payment_type_enum", "amount" integer, "total_per_month" integer, "total" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "property_id" uuid, CONSTRAINT "REL_578f581a41d0bc60ac6e7ed6f7" UNIQUE ("property_id"), CONSTRAINT "PK_a6ff5052357071a8ddd78c40b48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_number" character varying NOT NULL, "account_name" character varying NOT NULL, "bank_code" character varying, "bank_name" character varying, "bank_id" character varying, "payee_id" uuid NOT NULL, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "listed_elsewhere" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "user_id" uuid NOT NULL, "property_link" text NOT NULL, "property_address" text NOT NULL, "description" text, CONSTRAINT "PK_2b8374fedbfe566c38196e420fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request_call" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meta" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "user_id" uuid NOT NULL, "email" character varying NOT NULL, "phone_number" character varying NOT NULL, "preferred_call_time" character varying, "preferred_call_day" character varying, "is_email_overridden" boolean NOT NULL DEFAULT false, "is_phone_overridden" boolean NOT NULL DEFAULT false, "override_reason" character varying, "processed_at" TIMESTAMP WITH TIME ZONE, "processed_in_batch" character varying, CONSTRAINT "PK_7cb1297a7b2c9fe7dcf06a42df9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "paymentRates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_rate" numeric(5,2) NOT NULL, "property_agent_rate" numeric(5,2) NOT NULL, "platform_rate" numeric(5,2) NOT NULL, "range" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "propertyFee_id" uuid, CONSTRAINT "REL_a00731c2b2d97902d5355b0433" UNIQUE ("propertyFee_id"), CONSTRAINT "PK_988dcc0dfd2907c44b3b0fb0d82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "location_lga" ADD CONSTRAINT "FK_2ae1526d1e661aaac7180147483" FOREIGN KEY ("state_id") REFERENCES "location_state"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_wards" ADD CONSTRAINT "FK_3f82ece7183007b54ffb07b8462" FOREIGN KEY ("lga_id") REFERENCES "location_lga"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tour_request" ADD CONSTRAINT "FK_01765cc014cd25794782d5d7e8f" FOREIGN KEY ("property_id") REFERENCES "unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tour_request" ADD CONSTRAINT "FK_22083f904c2ed5dda60d86e9591" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tour_request" ADD CONSTRAINT "FK_ab97063e4462b50ae79c66ba2af" FOREIGN KEY ("user_details_id") REFERENCES "user_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property" ADD CONSTRAINT "FK_61769005fc1e66c57ea29f11fa0" FOREIGN KEY ("property_media_id") REFERENCES "property_media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit" ADD CONSTRAINT "FK_ffd1df4d8c19a8bd49fcd8af71b" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d05063db688ad262c5c7a7482c8" FOREIGN KEY ("user_details_id") REFERENCES "user_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" ADD CONSTRAINT "FK_698b726a6fdce0472c1876854bc" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" ADD CONSTRAINT "FK_1b28d36f03d08b5177eab13820c" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" ADD CONSTRAINT "FK_a752c1e03efdfafcbe75722c93d" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" ADD CONSTRAINT "FK_e54d9e3e71a9cc50914f2f61fe5" FOREIGN KEY ("user_details_id") REFERENCES "user_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_02f8e8d4094492641ad95010ca1" FOREIGN KEY ("payer_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_10578ef284a65afc54fb7c5aea3" FOREIGN KEY ("payee_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_c22819af2bbca819444f4f7aa76" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_85c5a451fd95da85400e6a182fa" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_580868f80b87cbbe8b1161eeed1" FOREIGN KEY ("request_to_rent_id") REFERENCES "request_to_rent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_464da95dc8a05470b2b158d4df6" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_fee" ADD CONSTRAINT "FK_578f581a41d0bc60ac6e7ed6f71" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_0407b57b1cedc9c3a0a1ed61407" FOREIGN KEY ("payee_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listed_elsewhere" ADD CONSTRAINT "FK_0150a96dae3b580b12f9129736c" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_call" ADD CONSTRAINT "FK_7f42181476a5deb112acd8b745c" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paymentRates" ADD CONSTRAINT "FK_a00731c2b2d97902d5355b0433b" FOREIGN KEY ("propertyFee_id") REFERENCES "property_fee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "paymentRates" DROP CONSTRAINT "FK_a00731c2b2d97902d5355b0433b"`);
        await queryRunner.query(`ALTER TABLE "request_call" DROP CONSTRAINT "FK_7f42181476a5deb112acd8b745c"`);
        await queryRunner.query(`ALTER TABLE "listed_elsewhere" DROP CONSTRAINT "FK_0150a96dae3b580b12f9129736c"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_0407b57b1cedc9c3a0a1ed61407"`);
        await queryRunner.query(`ALTER TABLE "property_fee" DROP CONSTRAINT "FK_578f581a41d0bc60ac6e7ed6f71"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_464da95dc8a05470b2b158d4df6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_580868f80b87cbbe8b1161eeed1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_85c5a451fd95da85400e6a182fa"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_c22819af2bbca819444f4f7aa76"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_10578ef284a65afc54fb7c5aea3"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_02f8e8d4094492641ad95010ca1"`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" DROP CONSTRAINT "FK_e54d9e3e71a9cc50914f2f61fe5"`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" DROP CONSTRAINT "FK_a752c1e03efdfafcbe75722c93d"`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" DROP CONSTRAINT "FK_1b28d36f03d08b5177eab13820c"`);
        await queryRunner.query(`ALTER TABLE "request_to_rent" DROP CONSTRAINT "FK_698b726a6fdce0472c1876854bc"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d05063db688ad262c5c7a7482c8"`);
        await queryRunner.query(`ALTER TABLE "unit" DROP CONSTRAINT "FK_ffd1df4d8c19a8bd49fcd8af71b"`);
        await queryRunner.query(`ALTER TABLE "property" DROP CONSTRAINT "FK_61769005fc1e66c57ea29f11fa0"`);
        await queryRunner.query(`ALTER TABLE "tour_request" DROP CONSTRAINT "FK_ab97063e4462b50ae79c66ba2af"`);
        await queryRunner.query(`ALTER TABLE "tour_request" DROP CONSTRAINT "FK_22083f904c2ed5dda60d86e9591"`);
        await queryRunner.query(`ALTER TABLE "tour_request" DROP CONSTRAINT "FK_01765cc014cd25794782d5d7e8f"`);
        await queryRunner.query(`ALTER TABLE "location_wards" DROP CONSTRAINT "FK_3f82ece7183007b54ffb07b8462"`);
        await queryRunner.query(`ALTER TABLE "location_lga" DROP CONSTRAINT "FK_2ae1526d1e661aaac7180147483"`);
        await queryRunner.query(`DROP TABLE "paymentRates"`);
        await queryRunner.query(`DROP TABLE "request_call"`);
        await queryRunner.query(`DROP TABLE "listed_elsewhere"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "property_fee"`);
        await queryRunner.query(`DROP TYPE "public"."property_fee_payment_type_enum"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_role_enum"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TYPE "public"."review_type_enum"`);
        await queryRunner.query(`DROP TABLE "service_fee_config"`);
        await queryRunner.query(`DROP TYPE "public"."service_fee_config_transaction_type_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payee_role_enum"`);
        await queryRunner.query(`DROP TABLE "request_to_rent"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "property_media"`);
        await queryRunner.query(`DROP TABLE "unit"`);
        await queryRunner.query(`DROP TYPE "public"."unit_status_enum"`);
        await queryRunner.query(`DROP TABLE "property"`);
        await queryRunner.query(`DROP TYPE "public"."property_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."property_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."property_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."property_lease_term_enum"`);
        await queryRunner.query(`DROP TABLE "tour_request"`);
        await queryRunner.query(`DROP TABLE "user_details"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP TYPE "public"."otp_otp_ref_type_enum"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_media_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_media_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_ref_category_enum"`);
        await queryRunner.query(`DROP TABLE "lessor_info"`);
        await queryRunner.query(`DROP TYPE "public"."lessor_info_lessor_category_enum"`);
        await queryRunner.query(`DROP TABLE "wishlist"`);
        await queryRunner.query(`DROP TABLE "kvp"`);
        await queryRunner.query(`DROP TYPE "public"."kvp_key_enum"`);
        await queryRunner.query(`DROP TABLE "waitlist"`);
        await queryRunner.query(`DROP TABLE "faq"`);
        await queryRunner.query(`DROP TYPE "public"."faq_type_enum"`);
        await queryRunner.query(`DROP TABLE "report_property"`);
        await queryRunner.query(`DROP TABLE "location_wards"`);
        await queryRunner.query(`DROP TABLE "location_lga"`);
        await queryRunner.query(`DROP TABLE "location_state"`);
        await queryRunner.query(`DROP TABLE "faq_question"`);
        await queryRunner.query(`DROP TABLE "donation"`);
        await queryRunner.query(`DROP TABLE "demo"`);
        await queryRunner.query(`DROP TABLE "contact_request"`);
    }

}
